name: build & Sync Amazon S3

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: Commit files
        run: |
          now=`date '+%Y%m%d%H%M'`
          year=`date '+%Y'`
          month=`date '+%m'`
          date=`date '+%d'`
          savepath="images/cam_KEIO-line_upper/$year/$month/$date/$now.jpg"
          url="https://www.ktr.mlit.go.jp/keihin/webcam/cam_KEIO-line_upper.jpg?${now}"
          commitmessage="画像を保存 ${now}"
          mkdir -p "images"
          mkdir -p "images/cam_KEIO-line_upper"
          mkdir -p "images/cam_KEIO-line_upper/${year}"
          mkdir -p "images/cam_KEIO-line_upper/${year}/${month}"
          mkdir -p "images/cam_KEIO-line_upper/${year}/${month}/${date}"
          curl -o $savepath $url
          git add .
          git commit -m commitmessage -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master